## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
df = application_df.drop(columns=['EIN'])

df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
df_name = df['NAME'].value_counts()
df_name

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [4]:
df_name[df_name > 50]

PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                        408
PTA TEXAS CONGRESS                                                     368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                          331
ALPHA PHI SIGMA                                                        313
TOASTMASTERS INTERNATIONAL                                             293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                      287
LITTLE LEAGUE BASEBALL INC                                             277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                               266
MOMS CLUB                                                              210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION     206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                               197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                   166
KNIGHTS OF COLUMBUS                                                    158
HABITAT FOR HUMANITY INTERNATIONAL INC                                 154
TENNESSEE ORDER OF THE EASTERN STAR                                    151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                144
PTA UTAH CONGRESS                                                      140
THE UNITED STATES PONY CLUBS INC                                       136
CIVITAN INTERNATIONAL                                                  131
SIGMA BETA DELTA INC                                                   127
HONOR SOCIETY OF PHI KAPPA PHI                                         107
MONTANA 4-H FOUNDATION INC                                             107
WASHINGTON STATE GRANGE                                                106
UNIVERSITY OF WYOMING                                                  105
DEMOLAY INTERNATIONAL                                                  104
SERTOMA INC                                                            103
AIR FORCE ASSOCIATION                                                   99
WORKERS UNITED                                                          97
GAMMA THETA UPSILON                                                     92
INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS                              91
SOCIETY OF SAINT VINCENT DE PAUL COUNCIL OF LOS ANGELES                 87
ROTARY INTERNATIONAL                                                    84
CALIFORNIA GARDEN CLUBS INC                                             76
SWEET ADELINES INTERNATIONAL                                            73
DISABLED AMERICAN VETERANS                                              73
KLEIN SUPPORT GROUPS INC                                                69
CLEARCREEK I S D SUPPORT GROUPS                                         60
VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC                                58
DEPARTMENT OF KANSAS LADIES AUXILIARY TO THE VFW OF THE US INC          57
CISD EDUCATIONAL SUPPORT GROUPS INC                                     57
SONS OF CONFEDERATE VETERANS INC                                        56
SLOW FOOD USA INC                                                       55
NATIONAL YOUNG MENS SERVICE LEAGUE                                      54
AMATEUR ATHLETIC UNION OF THE UNITED STATES                             52
LAMBDA THETA ALPHA                                                      52
Name: NAME, dtype: int64

In [5]:
name_to_replace = list(df_name[df_name <100].index)

In [6]:
for name in name_to_replace:
   df['NAME'] = df['NAME'].replace(name,"Other")


df['NAME'].value_counts()

Other                                                                 25987
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
HONOR SOCIETY OF PHI KAPPA PHI                                          107
MONTANA 4-H FOUNDATION INC                                              107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
Name: NAME, dtype: int64

In [7]:
# Determine the number of unique values in each column.
df.nunique()

NAME                        31
APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [8]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = df['APPLICATION_TYPE'].value_counts()

app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

application_types_to_replace = list(app_counts [app_counts < 500].index)
application_types_to_replace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [10]:
# Replace in dataframe
for app in application_types_to_replace:
    df['APPLICATION_TYPE'] = df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [11]:
# Look at CLASSIFICATION value counts for binning
class_counts = df['CLASSIFICATION'].value_counts()

class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [12]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [13]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

classifications_to_replace = list(class_counts[class_counts<1000].index)

In [14]:
# Replace in dataframe
for cls in classifications_to_replace:
    df['CLASSIFICATION'] = df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [15]:
# Convert categorical data to numeric with `pd.get_dummies`
dummy_df = pd.get_dummies(df)
list(dummy_df)

['STATUS',
 'ASK_AMT',
 'IS_SUCCESSFUL',
 'NAME_ALPHA PHI SIGMA',
 'NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC',
 'NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN',
 'NAME_CIVITAN INTERNATIONAL',
 'NAME_DEMOLAY INTERNATIONAL',
 'NAME_FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA',
 'NAME_HABITAT FOR HUMANITY INTERNATIONAL INC',
 'NAME_HONOR SOCIETY OF PHI KAPPA PHI',
 'NAME_INTERNATIONAL ASSOCIATION OF LIONS CLUBS',
 'NAME_INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION',
 'NAME_KNIGHTS OF COLUMBUS',
 'NAME_LITTLE LEAGUE BASEBALL INC',
 'NAME_MOMS CLUB',
 'NAME_MONTANA 4-H FOUNDATION INC',
 'NAME_MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS',
 'NAME_Other',
 'NAME_PARENT BOOSTER USA INC',
 'NAME_PTA TEXAS CONGRESS',
 'NAME_PTA UTAH CONGRESS',
 'NAME_SERTOMA INC',
 'NAME_SIGMA BETA DELTA INC',
 'NAME_SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC',
 'NAME_TENNESSEE ORDER OF THE EASTERN STAR',
 'NAME_THE UNITED STATES PONY CLUBS INC',
 'NAME_TOASTMASTERS INTERNATIONAL',
 'NAME_TOPS CLUB INC',
 'NAME_UNITED STATES BOWLING CONGRESS INC',
 'NAME_UNIVERSITY OF WYOMING',
 'NAME_VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY',
 'NAME_WASHINGTON STATE GRANGE',
 'NAME_WASHINGTON STATE UNIVERSITY',
 'APPLICATION_TYPE_Other',
 'APPLICATION_TYPE_T10',
 'APPLICATION_TYPE_T19',
 'APPLICATION_TYPE_T3',
 'APPLICATION_TYPE_T4',
 'APPLICATION_TYPE_T5',
 'APPLICATION_TYPE_T6',
 'APPLICATION_TYPE_T7',
 'APPLICATION_TYPE_T8',
 'AFFILIATION_CompanySponsored',
 'AFFILIATION_Family/Parent',
 'AFFILIATION_Independent',
 'AFFILIATION_National',
 'AFFILIATION_Other',
 'AFFILIATION_Regional',
 'CLASSIFICATION_C1000',
 'CLASSIFICATION_C1200',
 'CLASSIFICATION_C2000',
 'CLASSIFICATION_C2100',
 'CLASSIFICATION_C3000',
 'CLASSIFICATION_Other',
 'USE_CASE_CommunityServ',
 'USE_CASE_Heathcare',
 'USE_CASE_Other',
 'USE_CASE_Preservation',
 'USE_CASE_ProductDev',
 'ORGANIZATION_Association',
 'ORGANIZATION_Co-operative',
 'ORGANIZATION_Corporation',
 'ORGANIZATION_Trust',
 'INCOME_AMT_0',
 'INCOME_AMT_1-9999',
 'INCOME_AMT_10000-24999',
 'INCOME_AMT_100000-499999',
 'INCOME_AMT_10M-50M',
 'INCOME_AMT_1M-5M',
 'INCOME_AMT_25000-99999',
 'INCOME_AMT_50M+',
 'INCOME_AMT_5M-10M',
 'SPECIAL_CONSIDERATIONS_N',
 'SPECIAL_CONSIDERATIONS_Y']

In [16]:
# Split our preprocessed data into our features and target arrays
X = dummy_df.drop("IS_SUCCESSFUL",axis='columns').values
y = dummy_df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    random_state=78
)

In [17]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [24]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
features = len(X_train[0])
hidden_nodes1 = 80
hidden_nodes2 = 30
hidden_nodes3 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(
        units=hidden_nodes1,
        input_dim=features, activation="relu")
)

# Second hidden layer
nn.add(
    tf.keras.layers.Dense(
        units=hidden_nodes2, activation="relu"))

# Second hidden layer
nn.add(
    tf.keras.layers.Dense(
        units=hidden_nodes3, activation="relu"))

# Output layer
nn.add(
    tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_7 (Dense)             (None, 80)                6000

 dense_8 (Dense)             (None, 30)                2430

 dense_9 (Dense)             (None, 5)                 155

 dense_10 (Dense)            (None, 1)                 6

=================================================================
Total params: 8591 (33.56 KB)
Trainable params: 8591 (33.56 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [25]:
# Compile the model
nn.compile(
    loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [26]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5176 - accuracy: 0.7419
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4939 - accuracy: 0.7561
Epoch 3/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4897 - accuracy: 0.7597
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4879 - accuracy: 0.7603
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4878 - accuracy: 0.7596
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4856 - accuracy: 0.7586
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4854 - accuracy: 0.7606
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4846 - accuracy: 0.7614
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4844 - accuracy: 0.7606
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4830 - accuracy: 0.7623
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4832 - accuracy: 0.7634
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4819 - accuracy: 0.7635
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4821 - accuracy: 0.7633
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4813 - accuracy: 0.7630
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4810 - accuracy: 0.7638
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4802 - accuracy: 0.7652
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4803 - accuracy: 0.7642
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4801 - accuracy: 0.7647
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4804 - accuracy: 0.7636
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4797 - accuracy: 0.7640
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4796 - accuracy: 0.7655
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4790 - accuracy: 0.7653
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4787 - accuracy: 0.7650
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4784 - accuracy: 0.7659
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4780 - accuracy: 0.7652
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4782 - accuracy: 0.7657
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4778 - accuracy: 0.7657
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4778 - accuracy: 0.7660
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4772 - accuracy: 0.7672
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4768 - accuracy: 0.7672
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4769 - accuracy: 0.7655
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4768 - accuracy: 0.7660
Epoch 33/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4769 - accuracy: 0.7661
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4765 - accuracy: 0.7670
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4761 - accuracy: 0.7662
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4759 - accuracy: 0.7669
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4764 - accuracy: 0.7671
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4761 - accuracy: 0.7679
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4756 - accuracy: 0.7675
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4754 - accuracy: 0.7679
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4755 - accuracy: 0.7668
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4753 - accuracy: 0.7669
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4755 - accuracy: 0.7666
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4754 - accuracy: 0.7674
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4751 - accuracy: 0.7672
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4747 - accuracy: 0.7678
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4749 - accuracy: 0.7671
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4745 - accuracy: 0.7683
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4746 - accuracy: 0.7673
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4741 - accuracy: 0.7675
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4744 - accuracy: 0.7672
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4747 - accuracy: 0.7676
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4741 - accuracy: 0.7680
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4744 - accuracy: 0.7674
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4737 - accuracy: 0.7675
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4739 - accuracy: 0.7689
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4741 - accuracy: 0.7674
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4737 - accuracy: 0.7682
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4736 - accuracy: 0.7674
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4736 - accuracy: 0.7688
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4740 - accuracy: 0.7680
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4732 - accuracy: 0.7680
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4735 - accuracy: 0.7683
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4730 - accuracy: 0.7686
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4732 - accuracy: 0.7677
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4730 - accuracy: 0.7681
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4729 - accuracy: 0.7682
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4731 - accuracy: 0.7683
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4723 - accuracy: 0.7689
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4725 - accuracy: 0.7685
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4724 - accuracy: 0.7680
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4722 - accuracy: 0.7689
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4723 - accuracy: 0.7681
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4722 - accuracy: 0.7678
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4725 - accuracy: 0.7681
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4720 - accuracy: 0.7685
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4721 - accuracy: 0.7683
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4720 - accuracy: 0.7689
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4720 - accuracy: 0.7687
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4720 - accuracy: 0.7690
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4720 - accuracy: 0.7686
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4719 - accuracy: 0.7690
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4718 - accuracy: 0.7689
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4716 - accuracy: 0.7694
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4717 - accuracy: 0.7690
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4719 - accuracy: 0.7689
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4714 - accuracy: 0.7688
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4720 - accuracy: 0.7685
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4716 - accuracy: 0.7691
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4716 - accuracy: 0.7685
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4712 - accuracy: 0.7689
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4715 - accuracy: 0.7691
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4711 - accuracy: 0.7690
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4712 - accuracy: 0.7686
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4710 - accuracy: 0.7692
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4712 - accuracy: 0.7696
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4710 - accuracy: 0.7685
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4712 - accuracy: 0.7690
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4707 - accuracy: 0.7691
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4712 - accuracy: 0.7694

In [27]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5041 - accuracy: 0.7511 - 495ms/epoch - 2ms/step
Loss: 0.5040510892868042, Accuracy: 0.7511370182037354

In [22]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [55]:
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [76]:
g_model = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
                                     max_depth=1, random_state=0).fit(X_train, y_train)
g_pred = g_model.predict(X_test_scaled)

In [70]:
g_model.score(X_test_scaled, y_test)

0.7317784256559767

In [71]:
r_model = RandomForestClassifier(n_estimators=100, random_state=78)
gr_model = r_model.fit(X_train_scaled, y_train)
r_pred = r_model.predict(X_test_scaled)

In [75]:
accuracy_score(y_test,pred)

0.7372594752186589